-- Seed defect_library (run as service role in Supabase SQL editor)
INSERT INTO defect_library (code, category, element_section, name_pl, recommendation_template, typical_urgency, is_active)
VALUES
('REC-001','Czystość i porządek','B','Wyczyścić i zakonserwować zaśniedziałe złącza i przewody odprowadzające uziemiające (K)','K','III',true),
('REC-002','Czystość i porządek','B','Uprzątnąć pozostawione wewnątrz elektrowni przedmioty niezwiązane z pracą turbiny (K)','K','III',true),
('REC-003','Czystość i porządek','B','Uporządkować wnętrze turbiny z niepotrzebnych przedmiotów (K)','K','III',true),
('REC-004','Czystość i porządek','B','Przyciąć roślinność wokół elektrowni wiatrowej (K)','K','III',true),
('REC-005','Czystość i porządek','B','Oczyścić z zabrudzeń i owadów wnętrze elektrowni (K)','K','III',true),
('REC-006','Czystość i porządek','B','Oczyścić szafy z zabrudzeń wraz z zamontowaniem filtrów (K)','K','III',true),
('REC-007','Czystość i porządek','B','Uprzątnąć wnętrze elektrowni z przedmiotów niezwiązanych z pracą turbiny (K)','K','III',true),
('REC-008','Czystość i porządek','B','Zlokalizować i usunąć zabrudzenia oraz wycieki z przekładni i hamulca Yaw oraz grupy hydraulicznej (K)','K','III',true),
('REC-009','Czystość i porządek','B','Należy wyczyścić zabrudzenia w sekcji Yaw (K)','K','III',true),
('REC-010','Czystość i porządek','B','Oczyścić podesty z zabrudzeń w górnych sekcjach (K)','K','III',true),
('REC-011','Fundament i posadowienie','A','Wykonać nową powłokę izolacyjną w pasie skrajnym na zewnętrznej odkrytej części fundamentu (K)','K','III',true),
('REC-012','Fundament i posadowienie','A','Wykonać izolację poziomą odkrytej części fundamentu po stronie zewnętrznej (NB)','NB','III',true),
('REC-013','Fundament i posadowienie','A','Zaleca się odsunięcie upraw od fundamentu elektrowni oraz stacji kontenerowej (K)','K','II',true),
('REC-014','Fundament i posadowienie','A','Wykonać izolację przeciwwilgociową sekcji fundamentowej stacji kontenerowej (K)','K','III',true),
('REC-015','Fundament i posadowienie','A','Oczyścić fundament wewnątrz elektrowni z martwych owadów i innych zanieczyszczeń (K)','K','III',true),
('REC-016','Fundament i posadowienie','A','Wykonać izolację poziomą odkrytej części fundamentu na zewnątrz (NB)','NB','III',true),
('REC-017','Fundament i posadowienie','A','Wykonać konserwację izolacji pionowej sekcji fundamentowej stacji kontenerowej (K)','K','III',true),
('REC-018','Fundament i posadowienie','A','Zlokalizować źródło obecności wody w sekcji fundamentowej stacji kontenerowej i wykonać niezbędne izolacyjne roboty naprawcze wraz z osuszeniem dolnej sekcji stacji (NB)','NB','III',true),
('REC-019','Fundament i posadowienie','A','Uzupełnić ubytki warstwy uszczelniającej na styku zewnętrznej odkrytej części fundamentu i pierścienia stalowej wieży (K)','K','III',true),
('REC-020','Fundament i posadowienie','A','Zabezpieczyć antykorozyjnie górną część kołnierza wkładu fundamentowego oraz styk fundamentu z wieżą w obrębie śrub montażowych (K)','K','III',true),
('REC-021','Fundament i posadowienie','A','Wykonać ponownie izolację przeciwwilgociową części odkrytej fundamentu (K)','K','III',true),
('REC-022','Fundament i posadowienie','A','Zabezpieczyć antykorozyjnie styk wkładu kotwiącego oraz górna cześć kołnierza wkładu fundamentowego (K)','K','III',true),
('REC-023','Fundament i posadowienie','A','Wykonać ponownie izolację poziomą przeciwwilgociową części odkrytej fundamentu przy użyciu specjalistycznych środków (K)','K','III',true),
('REC-024','Fundament i posadowienie','A','Wykonać konserwację izolacji poziomej przeciwwilgociowej zewnętrznej odkrytej części fundamentu przy gruncie (K)','K','III',true),
('REC-025','Fundament i posadowienie','A','Wykonać izolację poziomą odkrytej części fundamentu turbiny po stronie zewnętrznej wraz z usunięciem skażeń biologicznych (K)','K','III',true),
('REC-026','Fundament i posadowienie','A','Przyciąć roślinność wokół fundamentu turbiny oraz stacji kontenerowej (K)','K','III',true),
('REC-027','Fundament i posadowienie','A','Wykonać izolację poziomą zewnętrznej odkrytej części fundamentu (NB)','NB','III',true),
('REC-028','Fundament i posadowienie','A','Zaleca się odsunięcie upraw od fundamentu elektrowni (K)','K','II',true),
('REC-029','Fundament i posadowienie','A','Z uwagi na nieskuteczność zastosowanych rozwiązań w zakresie izolacji zaleca się wykonanie nowej izolacji przeciwwodnej zewnętrznej odkrytej części fundamentu poprzez zastosowanie specjalistycznych technologii (NB): – zagruntowanie masą naprawczą do betonu tworzącą powłokę przepuszczalną dla pary wodnej i nieprzepuszczalną dla wody oraz zawilgocenia powstającego na skutek podciągania kapilarnego - nałożenie membrany ochronnej dla betonu odpornej na działanie promieni UV i naturalnych czynników zewnętrznych, - odtworzenie uszczelnienia elastycznego między stalową wieżą i fundamentem betonowym, - zabezpieczenie antykorozyjne pierwszej flanszy wieży nad nadlewką','K','III',true),
('REC-030','Fundament i posadowienie','A','Wykonać zaprawki antykorozyjne w okolicach śrub sekcji fundamentowej wewnątrz wieży (K)','K','III',true),
('REC-031','Fundament i posadowienie','A','Oczyścić fundament wewnątrz elektrowni z martwych owadów i zanieczyszczeń (K)','K','III',true),
('REC-032','Fundament i posadowienie','A','Wymienić uszkodzone osłony śrub na zewnętrznym pierścieniu łączącym wieżę z sekcją fundamentową (NB)','NB','III',true),
('REC-033','Fundament i posadowienie','A','Wykonać naprawy wylewki betonowej na styku łączenia fundamentu z elementem stalowym wieży (NB)','NB','III',true),
('REC-034','Fundament i posadowienie','A','Wykonać konserwację powłoki izolacji pionowej sekcji fundamentowej stacji pomiarowej przy okazji wykonywania większych robót konserwacyjnych (K)','K','III',true),
('REC-035','Fundament i posadowienie','A','Oczyścić z zabrudzeń zewnętrzną oraz wewnętrzną część fundamentu (K)','K','III',true),
('REC-036','Fundament i posadowienie','A','Wykonać naprawy powłoki przeciwwilgociowej na zewnętrznej odkrytej części fundamentu (K)','K','III',true),
('REC-037','Fundament i posadowienie','A','Wykonać naprawy spękań i odspojeń zewnętrznej części fundamentu (K)','K','III',true),
('REC-038','Fundament i posadowienie','A','Prowadzić obserwację zacieków czy nie ulegają powiększeniu i ewentualnie zlikwidować źródło wycieku oraz przy wykonywaniu większych prac serwisowych oczyścić powierzchnie fundamentu z zacieków oleju (K)','K','III',true),
('REC-039','Fundament i posadowienie','A','Uporządkować wnętrze turbiny z niepotrzebnych przedmiotów oraz oczyścić dolną sekcję fundamentową z zabrudzeń (K)','K','III',true),
('REC-040','Fundament i posadowienie','A','Wykonać nową izolację zewnętrznej odkrytej części fundamentu turbiny (K)','K','III',true),
('REC-041','Fundament i posadowienie','A','Wykonać nową izolację poziomą zewnętrznej odkrytej części fundamentu oraz izolacji pionowej na styku zewnętrznego fundamentu i elementu stalowej wieży, a także uzupełnić drobne ubytki masy uszczelniającej (NB)','NB','III',true),
('REC-042','Fundament i posadowienie','A','Uzupełnić brakującą śrubę w pierścieniu łączącym sekcję fundamentową z elementem wieży (NB)','NB','III',true),
('REC-043','Fundament i posadowienie','A','Wykonać izolację zewnętrznej odkrytej części fundamentu turbiny (K)','K','III',true),
('REC-044','Fundament i posadowienie','A','Wykonać poprawy izolacji przeciwwilgociowej sekcji fundamentowej stacji kontenerowej (K)','K','III',true),
('REC-045','Fundament i posadowienie','A','Oczyścić wnętrze turbiny w sekcji fundamentowej z zabrudzeń i robactwa oraz uporządkować wnętrze elektrowni z przedmiotów niezwiązanych z pracą turbiny (K)','K','III',true),
('REC-046','Fundament i posadowienie','A','Wykonać naprawy ubytków betonu na żelbetowym cokole fundamentowym (NB)','NB','III',true),
('REC-047','Fundament i posadowienie','A','Wykonać warstwę wyrównującą – usuwającą nierówności wierzchniej warstwy cokołu fundamentowego (NB)','NB','III',true),
('REC-048','Fundament i posadowienie','A','Wykonać konserwację w obrębie fundamentu oraz punktowych uszkodzeń warstwy lakierniczej w wyższych sekcjach (K)','K','III',true),
('REC-049','Fundament i posadowienie','A','Odtworzyć izolację pionową sekcji fundamentowej (K)','K','III',true),
('REC-050','Fundament i posadowienie','A','Zabezpieczyć antykorozyjnie zewnętrzną część wkładu kotwiącego wystającą poza cokół fundamentowy (K)','K','III',true),
('REC-051','Fundament i posadowienie','A','Osuszyć dolną sekcję fundamentową turbiny z zalegającej wody oraz prowadzić obserwacje po obfitych opadach deszczu w celu zlokalizowania i zlikwidowania źródła przecieku (K)','K','II',true),
('REC-052','Fundament i posadowienie','A','Wykonać izolację przeciwwilgociową pionową sekcji fundamentowej stacji kontenerowej (K)','K','III',true),
('REC-053','Fundament i posadowienie','A','Wyczyścić pierwszą flanszę w sekcji fundamentowej oraz w miarę możliwości poszycie wieży po wyciekach oleju (K)','K','III',true),
('REC-054','Fundament i posadowienie','A','Oczyścić dach i elewację stacji kontenerowej z zabrudzeń i skażeń biologicznych oraz wykonać konserwację izolacji pionowej sekcji fundamentowej stacji kontenerowej (K)','K','III',true),
('REC-055','Fundament i posadowienie','A','Wykonać izolację poziomą (przeciwwilgociową) części odkrytej fundamentu przy użyciu specjalistycznych środków (K)','K','III',true),
('REC-056','Fundament i posadowienie','A','Wykonać konserwację izolacji pionowej fundamentu stacji kontenerowej wraz z oczyszczeniem z roślinności opaski wokół stacji (K)','K','III',true),
('REC-057','Fundament i posadowienie','A','Uzupełnić brakujące śruby pierwszego pierścienia łączącego wieżę z sekcją fundamentową wewnątrz turbiny (NG)','NG','I',true),
('REC-058','Fundament i posadowienie','A','Zabezpieczyć antykorozyjnie lokalne ubytki powłok malarskich w okolicy pierwszego pierścienia łączącego wieże z sekcją fundamentową po stronie zewnętrznej (K)','K','III',true),
('REC-059','Fundament i posadowienie','A','Wyprofilować pochylone płyty betonowe wokół fundamentu stacji kontenerowej, aby spadek był na w kierunku od stacji (NB)','NB','II',true),
('REC-060','Fundament i posadowienie','A','Przyciąć roślinność wokół fundamentu elektrowni i stacji kontenerowej (K)','K','III',true),
('REC-061','Fundament i posadowienie','A','Wykonać konserwację powłoki malarskiej cokołu fundamentowego (K)','K','III',true),
('REC-062','Fundament i posadowienie','A','Wykonać wyrównanie i wypoziomowanie posadowienia stacji kontenerowej (NB)','NB','I',true),
('REC-063','Fundament i posadowienie','A','Wykonać zaprawki malarskie na zewnętrznym styku fundamentu i elementu stalowej wieży (K)','K','III',true),
('REC-064','Fundament i posadowienie','A','Przyciąć roślinność wokół fundamentu turbiny i stacji kontenerowej (K)','K','III',true),
('REC-065','Fundament i posadowienie','A','Oczyścić z roślinności opaskę wokół stacji pomiarowej oraz zakrzewienie wokół fundamentu elektrowni (K)','K','III',true),
('REC-066','Fundament i posadowienie','A','Przyciąć roślinność oraz usunąć zakrzewienia zlokalizowane wokół fundamentu turbiny (K)','K','III',true),
('REC-067','Fundament i posadowienie','A','Przyciąć roślinność wokół stacji kontenerowej oraz fundamentu turbiny (K)','K','III',true),
('REC-068','Fundament i posadowienie','A','Oczyścić fundament wewnątrz elektrowni z martwych owadów (K)','K','III',true),
('REC-069','Fundament i posadowienie','A','Wyprofilować powierzchnię terenu wokół elektrowni wiatrowej tak by poprawić odprowadzenie wody roztopowej i opadowej poza obrys fundamentu (NB)','NB','III',true),
('REC-070','Fundament i posadowienie','A','Wykonać uszczelnienie styku zewnętrznej odkrytej części fundamentu z podlewką betonową (dotyczy izolacji z papy) (K)','K','III',true),
('REC-071','Fundament i posadowienie','A','Oczyścić ze skażeń biologicznych oraz wykonać konserwację izolacji poziomej przeciwwilgociowej zewnętrznej odkrytej części fundamentu elektrowni (K)','K','III',true),
('REC-072','Fundament i posadowienie','A','Wykonać konserwację antykorozyjną na poziomych łączeniach segmentów wieży pierwszej flanszy w sekcji fundamentowej oraz wykonać zaprawki antykorozyjne odprysków występujących na powierzchni wieży (K)','K','III',true),
('REC-073','Fundament i posadowienie','A','Odkurzyć powierzchnię fundamentu wewnątrz elektrowni z martwych owadów i innych zanieczyszczeń (K)','K','III',true),
('REC-074','Fundament i posadowienie','A','Zabezpieczyć antykorozyjnie skorodowane elementy instalacji uziemiającej w sekcji fundamentowej turbiny (K)','K','III',true),
('REC-075','Fundament i posadowienie','A','Dokonać zabezpieczenia przeciwwilgociowego uszkodzonego fragmentu podlewki betonowej na styku połączenia ze stalowym elementem wieży (K)','K','III',true),
('REC-076','Fundament i posadowienie','A','Dokonać naprawy zakotwienia drabiny w części fundamentowej wieży elektrowni (NB)','NB','III',true),
('REC-077','Fundament i posadowienie','A','Poprawić uszczelnienie między stalową wieżą i fundamentem betonowym (K)','K','III',true),
('REC-078','Gondola i wirnik','A','Wymienić źródło światła w niedziałającej oprawie gondoli (K)','K','III',true),
('REC-079','Gondola i wirnik','A','Wymienić zabezpieczenie różnicowoprądowe 28F2, 28F1, 26F1 - pomiar wskazał błąd pomiaru oraz brak napięcia w gniazdku za szafą sterowniczą w gondoli (NB)','NB','II',true),
('REC-080','Gondola i wirnik','A','Wyczyścić smar na wale wolnoobrotowym wewnątrz gondoli (K)','K','III',true),
('REC-081','Gondola i wirnik','A','Wymienić zabezpieczenia różnicowoprądowego 28F2, 28F3 oraz przywrócenie napięcia w gniazdku za szafą sterowniczą w gondoli (NB)','NB','II',true),
('REC-082','Gondola i wirnik','A','Wykonać naprawy uszkodzonego szczebla od drabiny na odcinku od podestu windy do Gondoli (K)','K','III',true),
('REC-083','Gondola i wirnik','A','Wyczyścić podest w gondoli ze śladów wycieku oleju oraz zlokalizować ewentualne źródło zanieczyszczeń i dokonać niezbędnych napraw (K)','K','III',true),
('REC-084','Gondola i wirnik','A','Wykonać naprawy/wymiany uszkodzonej ramki włazu na zewnątrz gondoli (K)','K','III',true),
('REC-085','Inne','E','Dokonać naprawy uszkodzonego włazu wyjściowego na dach (K)','K','III',true),
('REC-086','Inne','E','Zlokalizować i zlikwidować źródło cieczy przy konstrukcji wsporczej transformatora - przy rożku uziemiającym (K)','K','III',true),
('REC-087','Inne','E','Wykonać naprawy/wymiany uszkodzonego obramowania włazu wyjściowego na dach (K)','K','III',true),
('REC-088','Inne','E','Wykonać naprawy/wymiany uszkodzonego włazu wyjściowego na dach (K)','K','III',true),
('REC-089','Inne','E','Dokręcić zamek od podestu przy cable loop pod sekcją Yaw (K)','K','III',true),
('REC-090','Inne','E','Wyczyścić zacieki w sekcji YAW (K)','K','III',true),
('REC-091','Inne','E','Wyczyścić smar na wale wolnoobrotowym oraz wyciek z przekładni (K)','K','III',true),
('REC-092','Inne','E','Wyczyścić smar na wale wolnoobrotowym oraz w sekcji YAW (K)','K','III',true),
('REC-093','Inne','E','Dokonać naprawy uszkodzonej ramki włazu wyjściowego na dach (K)','K','III',true),
('REC-094','Inne','E','Wykonać naprawy/wymiany uszkodzonego zabezpieczenia drabiny w sekcji YAW (K)','K','III',true),
('REC-095','Inne','E','Wymienić uszkodzoną stopkę drabiny w sekcji Yaw (K)','K','III',true),
('REC-096','Inne','E','Zabezpieczyć zarysowania krawędzi płyty dachowej (K)','K','III',true),
('REC-097','Instalacja elektryczna','C','Naprawa lub uzyskanie opinii projektanta instalacji elektrycznej turbiny wiatrowej o możliwości rezygnacji z ZK5 (NB)','NB','II',true),
('REC-098','Instalacja elektryczna','C','Wymienić zabezpieczenie gniazd serwisowych z charakterystyki C na charakterystykę B. Po wymianie zabezpieczenia wykonać kolejne pomiary elektryczne. (K)','K','II',true),
('REC-099','Instalacja elektryczna','C','Wymiana zabezpieczenia różnicowoprądowego 28X1 (NB)','NB','II',true),
('REC-100','Instalacja elektryczna','C','Wykonać niezbędne pomiary elektryczne po odtworzeniu instalacji uziemiającej (NB)','NB','I',true),
('REC-101','Instalacja elektryczna','C','Naprawa uszkodzonego uziemienia gniazda nN na poziomie nr 2 (NB)','NB','II',true),
('REC-102','Instalacja elektryczna','C','Naprawa uszkodzonego uziemienia gniazda nN na poziomie nr 1 (NB)','NB','II',true),
('REC-103','Instalacja elektryczna','C','Wymienić uszkodzony wyłącznik różnicowoprądowy 28X2(28F1) (NB)','NB','II',true),
('REC-104','Instalacja elektryczna','C','Naprawa uszkodzonego przewodu neutralnego gniazda nN na poziomie nr 3 (NB)','NB','II',true),
('REC-105','Instalacja elektryczna','C','Oczyścić wnętrze elektrowni z przedmiotów niezwiązanych z pracą turbiny (K)','K','III',true),
('REC-106','Izolacja i uszczelnienia','A','Wykonać konserwację izolacji pionowej stacji kontenerowej w pasie przyziemia (K)','K','III',true),
('REC-107','Izolacja i uszczelnienia','A','Wykonać poprawki uszczelnienia na poziomych łączeniach segmentów wieży wraz z konserwacją antykorozyjną wewnątrz i na zewnątrz wieży (K)','K','III',true),
('REC-108','Izolacja i uszczelnienia','A','Wykonać nową izolację pionową stacji kontenerowej w pasie przyziemia (K)','K','III',true),
('REC-109','Izolacja i uszczelnienia','A','Dokonać poprawek uszkodzonych fragmentów uszczelnienia na poziomym łączeniu segmentów wieży wraz z konserwacją antykorozyjną (w tym punktowe uszkodzenia powłoki lakierniczej na powierzchni wieży i łączenie wieży z pierścieniem śrubowym (K)','K','III',true),
('REC-110','Izolacja i uszczelnienia','A','Wykonać izolację poziomą przeciwwilgociową w górnej części żelbetowego cokołu (K)','K','III',true),
('REC-111','Izolacja i uszczelnienia','A','Dokonać poprawki uszczelnienia na poziomych łączeniach segmentów wieży wraz z konserwacją antykorozyjną (K)','K','III',true),
('REC-112','Izolacja i uszczelnienia','A','Dokonać poprawek uszkodzonych fragmentów warstwy uszczelniającej na poziomym łączeniu segmentów wieży wraz z konserwacją antykorozyjną (K)','K','III',true),
('REC-113','Izolacja i uszczelnienia','A','Wykonać konserwację izolacji pionowej stacji kontenerowej (K)','K','III',true),
('REC-114','Izolacja i uszczelnienia','A','Wykonać uszczelnienie na styku sekcji kotwiącej i pierwszego elementu wieży po zewnętrznej i wewnętrznej stronie (K)','K','III',true),
('REC-115','Izolacja i uszczelnienia','A','Oczyścić dach stacji kontenerowej ze skażeń biologicznych wraz z ewentualną poprawą lub wykonaniem izolacji przeciwwilgociowej oraz dokonać poprawy powłoki tynkarskiej (K)','K','III',true),
('REC-116','Izolacja i uszczelnienia','A','Oczyścić dach stacji kontenerowej ze skażeń biologicznych oraz wykonać lub ewentualnie poprawić izolację przeciwwilgociową dachu (K)','K','III',true),
('REC-117','Izolacja i uszczelnienia','A','Oczyścić dach ze skażeń biologicznych i ewentualnie poprawić izolację przeciwwilgociową dachu oraz wykonać naprawę zarysować powłok malarskich na elewacji stacji pomiarowej (K)','K','III',true),
('REC-118','Izolacja i uszczelnienia','A','Oczyścić dach ze skażeń biologicznych i wykonać izolację przeciwwilgociową dachu oraz wykonać konserwację powłok malarskich elewacji stacji pomiarowej (K)','K','III',true),
('REC-119','Izolacja i uszczelnienia','A','Wykonać naprawy wytartej izolacji pionowej stacji kontenerowej w pasie przyziemia oraz dokonać naprawy drobnych uszkodzeń tynku zewnętrznego wraz z usunięciem skażeń biologicznych oraz wulgarnych treści (K)','K','III',true),
('REC-120','Izolacja i uszczelnienia','A','Wykonać uzupełnienia masy uszczelniającej na poziomych łączeniach segmentów wieży wraz z konserwacją antykorozyjną (w tym czyszczeniem zacieków na powłoce lakierniczej) (K)','K','III',true),
('REC-121','Izolacja i uszczelnienia','A','Dokonać uzupełnień ubytków masy uszczelniającej na poziomym łączeniu segmentów wieży wraz z czyszczeniem zacieków i przebarwień (K)','K','III',true),
('REC-122','Izolacja i uszczelnienia','A','Dokonać poprawki uszkodzonych fragmentów uszczelnienia na poziomym łączeniu segmentów wieży wraz z konserwacją antykorozyjną (K)','K','III',true),
('REC-123','Izolacja i uszczelnienia','A','Wykonać uszczelnienia przepustów kablowych oraz styku segmentów stacji w celu wyeliminowania przedostawania się wody do wnętrza stacji (NB)','NB','III',true),
('REC-124','Oświetlenie','C','Wymiana gniazda elektrycznego oraz naprawa/wymiana źródła światła w uszkodzonych oprawach (NB)','NB','II',true),
('REC-125','Platforma i podest','B','Wymienić uszkodzony kluczyk wewnątrz podestu ruchomego (K)','K','III',true),
('REC-126','Platforma i podest','B','Oczyścić platformy i podesty z plam po oleju (K)','K','III',true),
('REC-127','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną łączników śrubowych schodów zewnętrznych (K)','K','III',true),
('REC-128','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną w okolicach kratki wentylacyjnej drzwi wejściowych do turbiny (K)','K','III',true),
('REC-129','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną łączników śrubowych na schodach zewnętrznych (K)','K','III',true),
('REC-130','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną uchwytów montażowych i łączników śrubowych na schodach zewnętrznych (K)','K','III',true),
('REC-131','Powłoki antykorozyjne','A','Wykonać zaprawki antykorozyjne na drzwiach zewnętrznych wraz z oczyszczeniem kratek wentylacyjnych (K)','K','III',true),
('REC-132','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną pierścienia pierwszego segmentu wieży (zewnątrz oraz wewnątrz) (K)','K','III',true),
('REC-133','Powłoki antykorozyjne','A','Wykonać zaprawki antykorozyjne na drzwiach zewnętrznych w okolicach kratki wentylacyjnej (K)','K','III',true),
('REC-134','Powłoki antykorozyjne','A','Wykonać zaprawki antykorozyjne na drzwiach zewnętrznych oraz na łącznikach śrubowych (K)','K','III',true),
('REC-135','Powłoki antykorozyjne','A','Zabezpieczyć antykorozyjnie styk elementu kotwiącego z pierwszym elementem rurowym oraz punktowe uszkodzenia powłoki lakierniczej na zewnętrznej powierzchni wieży (K)','K','III',true),
('REC-136','Powłoki antykorozyjne','A','Połączenia śrubowe połączeń wyrównawczych zabezpieczyć antykorozyjnie wazeliną techniczną, bezkwasową (K)','K','III',true),
('REC-137','Powłoki antykorozyjne','A','Wykonać zaprawki malarskie na krawędzi kołnierza w dolnej sekcji I segmentu wieży od strony zewnętrznej (K)','K','III',true),
('REC-138','Powłoki antykorozyjne','A','Wykonać zaprawki antykorozyjne punktowych odprysków na powierzchni zewnętrznej sekcji wieży oraz na łączeniach segmentów wewnątrz wieży (K)','K','III',true),
('REC-139','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną okolic drzwi wejściowych (w tym śrub oraz słupka wewnątrz wieży przy drzwiach) (K)','K','III',true),
('REC-140','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną drzwi wejściowych (łączniki śrubowe oraz kratka wentylacyjna od wewnętrznej strony) (K)','K','III',true),
('REC-141','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną kratki wentylacyjnej od wewnętrznej strony w drzwiach wejściowych do turbiny (K)','K','III',true),
('REC-142','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną punktowych uszkodzeń (odprysków) na powierzchni wieży po zewnętrznej stronie (K)','K','III',true),
('REC-143','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną drzwi wejściowych do turbiny w okolicy kratek wentylacyjnych (K)','K','III',true),
('REC-144','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną żaluzji wentylacyjnej w drzwiach wejściowych do turbiny (K)','K','III',true),
('REC-145','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną żaluzji wentylacyjnej drzwi wejściowych do turbiny wraz z oczyszczeniem siatki przeciw owadom w nich zamontowanych (K)','K','III',true),
('REC-146','Powłoki antykorozyjne','A','Wykonać punktowe zaprawki antykorozyjne na schodach prowadzących do turbiny (K)','K','III',true),
('REC-147','Powłoki antykorozyjne','A','Wykonać konserwację powłok malarskich zewnętrznych schodów (K)','K','III',true),
('REC-148','Powłoki antykorozyjne','A','Wykonać konserwację powłok malarskich na stykach elementów wieży na zewnątrz i wewnątrz obiektu (K)','K','III',true),
('REC-149','Powłoki antykorozyjne','A','Wykonać konserwację powłok malarskich po zewnętrznej stronie wieży w obrębie połączenia z cokołem (K)','K','III',true),
('REC-150','Powłoki antykorozyjne','A','Wykonać konserwację powłok malarskich stalowych drzwi stacji kontenerowej, w tym progu wewnątrz stacji (K)','K','III',true),
('REC-151','Powłoki antykorozyjne','A','Wykonać konserwację powłok malarskich balustrad i pochwytów oraz drzwi wejściowych do wieży w okolicach kratki wentylacyjnej (K)','K','III',true),
('REC-152','Powłoki antykorozyjne','A','Wykonać zaprawki antykorozyjne drzwi stacji kontenerowej (K)','K','III',true),
('REC-153','Powłoki antykorozyjne','A','Zabezpieczyć antykorozyjnie łączniki śrubowe schodów wejściowych do turbiny (K)','K','III',true),
('REC-154','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną powłoki malarskiej furtki prowadzącej na teren elektrowni (K)','K','III',true),
('REC-155','Powłoki antykorozyjne','A','Zabezpieczyć antykorozyjnie skorodowane elementy schodów zewnętrznych prowadzących do turbiny (K)','K','III',true),
('REC-156','Powłoki antykorozyjne','A','Wykonać konserwację powłok malarskich cokołu (K)','K','III',true),
('REC-157','Powłoki antykorozyjne','A','Wykonać konserwację ubytków malarskich schodów z balustradami prowadzących do turbiny (K)','K','III',true),
('REC-158','Powłoki antykorozyjne','A','Zabezpieczyć antykorozyjnie łączniki śrubowe schodów zewnętrznych prowadzących do turbiny, oraz lokalne odpryski powłok malarskich w rejonie drzwi wejściowych do turbiny (K)','K','III',true),
('REC-159','Powłoki antykorozyjne','A','Usunąć ognisko korozji i pomalować wspornik od schodów zewnętrznych oraz okolic drzwi wewnątrz turbiny (K)','K','III',true),
('REC-160','Powłoki antykorozyjne','A','Wymienić skorodowane śruby montażowe schodów i zawiasu oraz wykonać konserwację antykorozyjną poręczy schodów prowadzących do turbiny (K)','K','III',true),
('REC-161','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną drzwi stacji pomiarowej (K)','K','III',true),
('REC-162','Powłoki antykorozyjne','A','Wykonać konserwację punktowych ubytków powłok malarskich zewnętrznej części wieży wraz z zabezpieczeniem antykorozyjnym (K)','K','III',true),
('REC-163','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną ościeży drzwi wejściowych do elektrowni (K)','K','III',true),
('REC-164','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną metalowego wspornika i siłownika drzwi zewnętrznych (K)','K','III',true),
('REC-165','Powłoki antykorozyjne','A','Wykonać konserwację antykorozyjną na zewnętrznej części pierwszej flanszy (K)','K','III',true),
('REC-166','Schody, drzwi, wejście','B','Wymienić uszkodzoną uszczelkę w drzwiach wejściowych (NB)','NB','III',true),
('REC-167','Schody, drzwi, wejście','B','Przyciąć roślinność wokół elektrowni oraz stacji kontenerowej (w tym usunąć zakrzewienia przy schodach prowadzących na plac, na których są one posadowione (K)','K','III',true),
('REC-168','Schody, drzwi, wejście','B','Dokonać naprawy/wymiany uszczelki drzwi zewnętrznych do turbiny (K)','K','III',true),
('REC-169','Schody, drzwi, wejście','B','Zakotwić schody zewnętrzne wejściowe do turbiny (NB)','NB','II',true),
('REC-170','Schody, drzwi, wejście','B','Usunąć gniazdo owadów znajdujące się wewnątrz drzwi wejściowych do stacji pomiarowej (K)','K','II',true),
('REC-171','Schody, drzwi, wejście','B','Wyczyścić miejsce przecięcia uszczelki w dolnej części drzwi celem umożliwienia odpływu gromadzącej się tam wody i zapobiegnięcia przelewania się jej do wnętrza elektrowni (K)','K','III',true),
('REC-172','Schody, drzwi, wejście','B','Wymienić uszkodzone połączenie wyrównawcze w drzwiach wejściowych (K)','K','II',true),
('REC-173','Schody, drzwi, wejście','B','Wymienić uszkodzoną uszczelkę drzwi zewnętrznych do turbiny (K)','K','III',true),
('REC-174','Schody, drzwi, wejście','B','Wykonać wymiany uszkodzonej uszczelki w drzwiach wejściowych (K)','K','III',true),
('REC-175','Schody, drzwi, wejście','B','Wymienić uszkodzoną uszczelkę w drzwiach wejściowych oraz dokonać naprawy uszkodzonego daszku nad wejściem do turbiny (K)','K','II',true),
('REC-176','Schody, drzwi, wejście','B','Wymienić uszkodzoną uszczelkę w drzwiach wejściowych wraz z oczyszczeniem z zabrudzeń, a także dokonać naprawy uszkodzonego daszku nad wejściem do turbiny oraz połączenia wyrównawczego drzwi wejściowych (K)','K','II',true),
('REC-177','Schody, drzwi, wejście','B','Wymienić uszkodzoną uszczelkę w drzwiach wejściowych (K)','K','III',true),
('REC-178','Schody, drzwi, wejście','B','Uzupełnić brakującą śrubę na platformie przy wejściu (K)','K','III',true),
('REC-179','Schody, drzwi, wejście','B','Wykonać naprawy uszkodzonej siatki zabezpieczającej w kratce wentylacyjnej drzwi zewnętrznych (K)','K','III',true),
('REC-180','Schody, drzwi, wejście','B','Wymienić uszkodzoną gałkę drzwi zewnętrznych (NB)','NB','III',true),
('REC-181','Schody, drzwi, wejście','B','Wykonać prawidłowy montaż uszczelki drzwi zewnętrznych turbiny (K)','K','III',true),
('REC-182','Schody, drzwi, wejście','B','Dokonać naprawy/wymiany uszkodzonej gałki drzwi zewnętrznych (NB)','NB','III',true),
('REC-183','Schody, drzwi, wejście','B','Oczyścić kratki wentylacyjne drzwi zewnętrznych (K)','K','III',true),
('REC-184','Schody, drzwi, wejście','B','Dokonać naprawy/wymiany zamka drzwi zewnętrznych (NB)','NB','I',true),
('REC-185','Schody, drzwi, wejście','B','Wykonać naprawę pokrywy włazu na pierwszym podeście nad wejściem do turbiny (K)','K','III',true),
('REC-186','Schody, drzwi, wejście','B','Oczyścić wnętrze stacji kontenerowej z zabrudzeń, w tym drzwi wejściowe (K)','K','III',true),
('REC-187','Schody, drzwi, wejście','B','Usunąć gniazdo owadów znajdujące się nad drzwiami wejściowymi do stacji pomiarowej (K)','K','II',true),
('REC-188','Schody, drzwi, wejście','B','Poprawić montaż zamku w drzwiach zewnętrznych (K)','K','III',true),
('REC-189','Schody, drzwi, wejście','B','Uzupełnić zamek o stalową „listwę” umożliwiającą otwieranie drzwi od wewnątrz (NB)','NB','III',true),
('REC-190','Schody, drzwi, wejście','B','Wykonać naprawy uszkodzonego ogranicznika drzwi wejściowych do stacji kontenerowej (NB)','NB','III',true),
('REC-191','Schody, drzwi, wejście','B','Wymienić uszczelki drzwi wejściowych do turbiny oraz dokonać oczyszczenia i konserwacji po wewnętrznej stronie drzwi (K)','K','III',true),
('REC-192','Stacja kontenerowa/pomiarowa','E','Oczyścić wnętrze stacji kontenerowej z zabrudzeń (K)','K','III',true),
('REC-193','Stacja kontenerowa/pomiarowa','E','Przyciąć roślinność wokół stacji pomiarowej oraz turbiny (K)','K','III',true),
('REC-194','Stacja kontenerowa/pomiarowa','E','Oczyścić wnętrze stacji pomiarowej z zabrudzeń (K)','K','III',true),
('REC-195','Stacja kontenerowa/pomiarowa','E','Zlokalizować i usunąć przyczynę powstawania zawilgoceń w dolnej sekcji stacji kontenerowej (NB)','NB','II',true),
('REC-196','Stacja kontenerowa/pomiarowa','E','Oczyścić wnętrze stacji z zanieczyszczeń (K)','K','III',true),
('REC-197','Stacja kontenerowa/pomiarowa','E','Oczyścić wnętrze stacji kontenerowej z zabrudzeń oraz przedmiotów niezwiązanych z funkcjonowaniem stacji (K)','K','III',true),
('REC-198','Stacja kontenerowa/pomiarowa','E','Wykonać roboty naprawcze w celu zabezpieczenia dolnej sekcji stacji kontenerowej przed zalewaniem wody (NB)','NB','II',true),
('REC-199','Stacja kontenerowa/pomiarowa','E','Wykonać pomiary elektryczne wraz z przeglądem elektrycznym turbin i stacji pomiarowej','K','I',true),
('REC-200','Stacja kontenerowa/pomiarowa','E','Wykonać naprawy płyty dennej stacji kontenerowej (NB)','NB','II',true),
('REC-201','Stacja kontenerowa/pomiarowa','E','Wyczyścić piwnicę kablową stacji z zalegającego gruntu, zlokalizować i zlikwidować źródło zanieczyszczeń piwnicy kablowej stacji (K)','K','III',true),
('REC-202','Stacja kontenerowa/pomiarowa','E','Oczyścić dach stacji kontenerowej ze skażeń biologicznych udrożnić odpływ wody z dachu (K)','K','III',true),
('REC-203','Stacja kontenerowa/pomiarowa','E','Dokonać naprawy drobnych uszkodzeń tynku zewnętrznego stacji kontenerowej oraz usunąć skażenia biologiczne (K)','K','III',true),
('REC-204','Stacja kontenerowa/pomiarowa','E','Oczyścić z zabrudzeń i zanieczyszczeń wnętrze stacji kontenerowej (K)','K','III',true),
('REC-205','Stacja kontenerowa/pomiarowa','E','Zaleca się odsunięcie upraw od stacji kontenerowej (K)','K','II',true),
('REC-206','Stacja kontenerowa/pomiarowa','E','Oczyścić wnętrze stacji z zanieczyszczeń, zabrudzeń oraz uszkodzonych urządzeń elektroenergetycznych (K)','K','III',true),
('REC-207','Stacja kontenerowa/pomiarowa','E','Oczyścić wnętrze stacji z zanieczyszczeń i zabrudzeń wraz z uporządkowaniem otoczenia stacji i usunięciem zakrzewień, śmieci i kamieni (K)','K','III',true),
('REC-208','Stacja kontenerowa/pomiarowa','E','Oczyścić wnętrze stacji z zanieczyszczeń, zabrudzeń oraz zdemontowanych urządzeń elektroenergetycznych (K)','K','III',true),
('REC-209','Stacja kontenerowa/pomiarowa','E','Uporządkować teren wokół stacji oraz turbiny (przyciąć roślinność) (K)','K','III',true),
('REC-210','Stacja kontenerowa/pomiarowa','E','Wykonać naprawy pęknięć tynku zewnętrznego stacji elektroenergetycznej oczyścić elewacje z zabrudzeń i skażeń biologicznych (K)','K','III',true),
('REC-211','Stacja kontenerowa/pomiarowa','E','Oczyścić z zabrudzeń i owadów wnętrze stacji pomiarowej oraz elektrowni (K)','K','III',true),
('REC-212','Stacja kontenerowa/pomiarowa','E','Dokonać przycięcia traw i chwastów wokół turbiny i stacji pomiarowej oraz usunąć zakrzewienia zlokalizowane przy stacji pomiarowej (K)','K','III',true),
('REC-213','Wieża','A','Oczyścić podesty oraz inne zabrudzone elementy wyposażenia turbiny z zabrudzeń środkami smarnymi zlokalizowanych w górnych sekcjach wieży (K)','K','III',true),
('REC-214','Wieża','A','Oczyścić podesty z zabrudzeń w górnych sekcjach wieży (K)','K','III',true),
('REC-215','Wieża','A','Oczyścić z zabrudzeń podesty w górnych sekcjach wieży (K)','K','III',true),
('REC-216','Wieża','A','Wymiana zabezpieczenia nadprądowego na obwodzie zasilającym gniazda w wieży na zabezpieczenie o innej charakterystyce lub wymiana oprzewodowania gniazd w wieży (NB)','NB','I',true),
('REC-217','Wieża','A','Zabezpieczyć miejsce przejścia stalowej liny podestu ruchomego przez platformę (podest) wewnątrz wieży (K)','K','III',true),
('REC-218','Wieża','A','Wymienić źródło światła w niedziałającej oprawie we wnętrzu wieży (K)','K','III',true),
('REC-219','Wieża','A','Oczyścić z zabrudzeń podesty w wyższych sekcjach wieży (K)','K','III',true),
('REC-220','Wieża','A','Oczyścić widoczne zabrudzenia powłoki lakierniczej w obrębie pierwszego segmentu wieży (K)','K','III',true),
('REC-221','Wieża','A','Zabezpieczyć wywiercone na wylot otwory w wieży turbiny (K)','K','II',true),
('REC-222','Wieża','A','Uporządkować przestrzeń wewnątrz wieży w rejonie styku części żelbetowej i stalowej - uporządkować pozostawione tam przedmioty oraz prawidłowo zabezpieczyć dostęp do wnętrza żelbetowego cokołu – żelbetowej części wieży (K)','K','III',true),
('REC-223','Wieża','A','Oczyścić zewnętrzną powierzchnię wieży w miarę możliwości z zabrudzeń wynikających z wycieku oleju (K)','K','III',true),
('REC-224','Wieża','A','Oczyścić z nadmiaru smaru powierzchnię wieży w górnych sekcjach wewnątrz turbiny (K)','K','III',true),
('REC-225','Wieża','A','Oczyścić z zabrudzeń i pozostawionych uszczelek platformy i podesty w górnych sekcjach wieży oraz wnętrze gondoli z zabrudzeń i wycieków (K)','K','III',true),
('REC-226','Wieża','A','Oczyścić z zabrudzeń platformy i podesty w górnych sekcjach wieży oraz wnętrze gondoli z zabrudzeń i wycieków (K)','K','III',true),
('REC-227','Wieża','A','Usunąć plamy oleju na platformach i podestach wewnątrz wieży (K)','K','III',true),
('REC-228','Wieża','A','Usunąć usterkę braku uziemienia gniazd zainstalowanych na najwyższym poziomie wieży oraz gondoli (K)','K','II',true),
('REC-229','Wieża','A','Oczyścić podesty w górnych sekcjach wieży z zabrudzeń (K)','K','III',true),
('REC-230','Wieża','A','Oczyścić podesty z zabrudzeń w górnych sekcjach wieży, wyczyścić smar na wale wolnoobrotowym oraz w sekcji YAW, a także ślady po smarze w okolicy połączeń śrubowych (K)','K','III',true),
('REC-231','Wieża','A','Dokonać wymiany uszkodzonej drabiny w sekcji YAW – widoczna nowa drabina pozostawiona wewnątrz wieży na wymianę (K)','K','III',true),
('REC-232','Wieża','A','Oczyścić podesty oraz okolice połączeń śrubowych wewnątrz wieży z zabrudzeń (K)','K','III',true),
('REC-233','Wieża','A','Oczyścić podesty z zabrudzeń w górnych sekcjach wieży oraz w sekcji YAW, wyczyścić podest w gondoli ze śladów wycieku oleju, a także zlokalizować ewentualne źródło zanieczyszczeń i dokonać niezbędnych napraw (K)','K','III',true),
('REC-234','Wieża','A','Oczyścić z zabrudzeń podesty wewnątrz wieży oraz zlokalizować i usunąć zabrudzenia i wycieki z przekładni i hamulców w sekcji Yaw (K)','K','III',true),
('REC-235','Wieża','A','Oczyścić z zabrudzeń podesty wewnątrz wieży w górnych sekcjach (K)','K','III',true),
('REC-236','Wieża','A','Oczyścić z zabrudzeń podesty wraz z balustradami w górnych sekcjach wieży (K)','K','III',true),
('REC-237','Wieża','A','Oczyścić podesty i balustrady oraz inne zabrudzone elementy wyposażenia turbiny z zabrudzeń środkami smarnymi zlokalizowanych w górnych sekcjach wieży (K)','K','III',true),
('REC-238','Wieża','A','Oczyścić podesty i barierki oraz inne zabrudzone elementy wyposażenia turbiny z zabrudzeń środkami smarnymi zlokalizowanych w górnych sekcjach wieży (K)','K','III',true),
('REC-239','Wieża','A','Oczyścić podesty, barierki oraz inne zabrudzone elementy wyposażenia turbiny z zabrudzeń środkami smarnymi zlokalizowanych w górnych sekcjach wieży (K)','K','III',true),
('REC-240','Wieża','A','Wymienić uszkodzone gniazdo nN na poziomie 1 wieży (NB)','NB','II',true),
('REC-241','Śruby i osłony','A','Wykonać naprawy uszkodzonego mocowania elementu osłony otworu wentylacyjnego po zewnętrznej stronie turbiny (NB)','NB','II',true),
('REC-242','Śruby i osłony','A','Zamontować osłony śrub przy głównym łożysku w gondoli (K)','K','III',true),
('REC-243','Śruby i osłony','A','Oczyścić podesty z zabrudzeń oraz uprzątnąć metalowy element osłony pozostawiony na jednej z platform (K)','K','III',true),
('REC-244','Śruby i osłony','A','Uzupełnić brakującą osłonę śruby mocowania łopaty z piastą wirnika (K)','K','III',true)
ON CONFLICT (code) DO UPDATE SET
  category = EXCLUDED.category,
  name_pl = EXCLUDED.name_pl,
  recommendation_template = EXCLUDED.recommendation_template,
  typical_urgency = EXCLUDED.typical_urgency,
  is_active = EXCLUDED.is_active;
